/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nkzn' at '15/07/25 21:31' with Gradle 2.5
 *
 * @author nkzn, @date 15/07/25 21:31
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
